project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "NYC Crime County Insights"
  author:
    - Kanisha Shah (ks4175)
    - Dhruvi Shah (dms2338)
  repo-url: https://github.com/Kanisha-Shah/NYC-Crimson-County-Insights
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


