# Interactive graph
<head>
<style>
  * {
    font-family: sans-serif;
  }
</style> 

<style>
  #selectButton {
    margin-top: 20px;
    font-family: 'Arial', sans-serif;
  }

  select {
    padding: 10px;
    font-size: 14px;
    border: 1px solid #ccc;
    border-radius: 5px;
    outline: none;
    cursor: pointer;
  }

  select:hover {
    background-color: #f0f0f0;
  }

  select:focus {
    border-color: #4CAF50;
    box-shadow: 0 0 5px rgba(76, 175, 80, 0.5);
  }
</style>

<div id="selectButton"></div>
<div id="plot">
</div>

<script src="https://cdn.jsdelivr.net/npm/d3@7"></script>
<script src="scripts/myscript.js"></script>
</head>

Inference From Graph

In dissecting the data through our d3 graph focused on Property Crimes over selected years, a compelling trend emerges – a substantial and consistent decrease in both violent crimes and property-related offenses. While the overall decline is noteworthy, a deeper analysis underscores a pivotal factor contributing to this positive trajectory – the marked reduction in property-related crimes.

The data paints a vivid picture of an improving safety landscape within New York City, particularly in the realm of property offenses. This decline suggests successful efforts in crime prevention, law enforcement strategies, and community engagement, all converging to create a more secure urban environment. While the reduction in violent crimes is commendable, the noteworthy decrease in property-related offenses signifies a tangible impact on the daily lives and well-being of New York City residents.

The insights gleaned from this analysis not only celebrate the positive strides in enhancing safety but also prompt further exploration into the specific interventions and policies that have catalyzed this decline. Understanding these contributing factors can pave the way for informed decision-making, resource allocation, and the continued pursuit of effective strategies to sustain and build upon this encouraging trend.
